version: '3'

services:
  db:
    container_name: mean-db
    image: mongo:5.0.16
    volumes:
      - /home/danny2768/git/Udemy/Angular/12-nest-backend/mongo/data/db:/data/db
    ports:
      - 27017:27017
    restart: always
